# Generated by Django 5.0.3 on 2024-03-04 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("type", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
