# Generated by Django 5.0.3 on 2024-03-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agency",
            old_name="type",
            new_name="type_of_agency",
        ),
    ]
